name: Updater

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push aocserver
        uses: docker/build-push-action@v3
        with:
          context: ./server/
          push: true
          tags: ghcr.io/schlauer-hax/advent-of-code:server

      - name: Build and push aocts
        uses: docker/build-push-action@v3
        with:
          context: ./clients/typescript/
          push: true
          tags: ghcr.io/schlauer-hax/advent-of-code:ts

      - name: Build and push aocjava
        uses: docker/build-push-action@v3
        with:
          context: ./clients/java/
          push: true
          tags: ghcr.io/schlauer-hax/advent-of-code:java
