name: Updater

on:
  push:
    branches: [master]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push aocserver
        uses: docker/build-push-action@v3
        with:
          context: ./server/
          push: true
          tags: ghcr.io/schlauer-hax/aoc-server
          labels: |
            org.opencontainers.image.source="https://github.com/Schlauer-Hax/advent-of-code"

      - name: Build and push aocts
        uses: docker/build-push-action@v3
        with:
          context: ./clients/typescript/
          push: true
          tags: ghcr.io/schlauer-hax/aoc-ts
          labels: |
            org.opencontainers.image.source="https://github.com/Schlauer-Hax/advent-of-code"

      - name: Build and push aocjava
        uses: docker/build-push-action@v3
        with:
          context: ./clients/java/
          push: true
          tags: ghcr.io/schlauer-hax/aoc-java
          labels: |
            org.opencontainers.image.source="https://github.com/Schlauer-Hax/advent-of-code"

      - name: Deploying to Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: /root/advent-of-code/deploy.sh
